# Generated by Django 2.2.14 on 2020-08-01 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('name', models.CharField(help_text='Name of the Department', max_length=255, verbose_name='Department Name')),
            ],
            options={
                'verbose_name': 'Department Name',
                'verbose_name_plural': 'Department Names',
            },
        ),
        migrations.CreateModel(
            name='CentreDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('about', models.TextField(blank=True, help_text='Description of the Department', null=True)),
                ('dept_name', models.ForeignKey(help_text='Name of the Department', on_delete=django.db.models.deletion.PROTECT, to='department.DepartmentName', verbose_name='Department Name')),
                ('dept_poc', models.OneToOneField(help_text='Point of Contact from the Department', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Point of Contact')),
            ],
            options={
                'verbose_name': 'Centre Department',
                'verbose_name_plural': 'Centre Departments',
            },
        ),
        migrations.CreateModel(
            name='StateDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('state', models.CharField(choices=[('KA', 'Karnataka'), ('AP', 'Andhra Pradesh'), ('KL', 'Kerala'), ('TN', 'Tamil Nadu'), ('MH', 'Maharashtra'), ('UP', 'Uttar Pradesh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('RJ', 'Rajasthan'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('TG', 'Telangana'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chattisgarh'), ('HR', 'Haryana'), ('JH', 'Jharkhand'), ('MP', 'Madhya Pradesh'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Orissa'), ('PB', 'Punjab'), ('SK', 'Sikkim'), ('TR', 'Tripura'), ('UA', 'Uttarakhand'), ('WB', 'West Bengal'), ('AN', 'Andaman and Nicobar'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('LD', 'Lakshadweep'), ('PY', 'Pondicherry')], max_length=25)),
                ('about', models.TextField(blank=True, help_text='Description of the Department', null=True)),
                ('dept_name', models.ForeignKey(help_text='Name of the Department', on_delete=django.db.models.deletion.PROTECT, to='department.DepartmentName', verbose_name='Department Name')),
                ('dept_poc', models.OneToOneField(help_text='Point of Contact from the Department', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Point of Contact')),
            ],
            options={
                'verbose_name': 'State Department',
                'verbose_name_plural': 'State Departments',
                'unique_together': {('dept_name', 'state')},
            },
        ),
    ]
