# Generated by Django 2.2.14 on 2020-08-01 08:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import schemes.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('name', models.CharField(help_text='Name of the Scheme', max_length=255, verbose_name='Scheme Name')),
                ('date_of_launching', models.DateField(help_text='When the scheme will be launched', verbose_name='Date of Launching')),
                ('description', models.TextField(verbose_name='Scheme Description')),
                ('slug', models.SlugField(blank=True, help_text='To create unique urls for the schemes', max_length=100, null=True, unique=True)),
                ('scheme_budget', models.DecimalField(decimal_places=2, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total Budget of the Scheme(in cr.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Scheme Active?')),
                ('created_by', models.ForeignKey(help_text='Which Department Created this Scheme', on_delete=django.db.models.deletion.PROTECT, to='department.CentreDepartment', verbose_name='Scheme Created By')),
            ],
            options={
                'verbose_name': 'Scheme',
                'verbose_name_plural': 'Schemes',
            },
        ),
        migrations.CreateModel(
            name='FundRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('description', models.TextField(verbose_name='Proposal Brief')),
                ('document', models.FileField(blank=True, null=True, upload_to='proposals/', validators=[schemes.validators.validate_file_extension], verbose_name='Proposal Document')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total Funds Required(in cr.)')),
                ('status', models.CharField(blank=True, choices=[('N', 'New'), ('IP', 'In Process'), ('R', 'Rejected'), ('D', 'Disbursed')], default='N', max_length=15, null=True, verbose_name='Status of the Request')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='department.StateDepartment', verbose_name='Requested By')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schemes.Scheme', verbose_name='Scheme')),
            ],
            options={
                'verbose_name': 'Fund Request',
                'verbose_name_plural': 'Fund Requests',
                'unique_together': {('scheme', 'created_by')},
            },
        ),
    ]
