# Generated by Django 2.2.14 on 2020-08-02 05:36

from django.db import migrations, models
import schemes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='proposals/', validators=[schemes.validators.validate_file_extension, schemes.validators.file_size], verbose_name='Proposal Document'),
        ),
    ]
