# Generated by Django 2.2.14 on 2020-08-02 07:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import schemes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('schemes', '0002_auto_20200802_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeFundRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('name', models.CharField(help_text='Name of the Scheme', max_length=255, verbose_name='Scheme Name')),
                ('date_of_launching', models.DateField(help_text='When the scheme will be launched', verbose_name='Date of Launching')),
                ('description', models.TextField(verbose_name='Scheme Description')),
                ('document', models.FileField(blank=True, null=True, upload_to='proposals/', validators=[schemes.validators.validate_file_extension, schemes.validators.file_size], verbose_name='Proposal Document')),
                ('funds_required', models.DecimalField(decimal_places=2, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total Funds required for the Scheme(in cr.)')),
                ('status', models.CharField(blank=True, choices=[('N', 'New'), ('IP', 'In Process'), ('R', 'Rejected'), ('D', 'Disbursed')], default='N', max_length=15, null=True, verbose_name='Status of the Request')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments will be added by centre/state officials regarding this scheme.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='department.StateDepartment', verbose_name='Which department created this scheme')),
            ],
            options={
                'verbose_name': 'Scheme Fund Request By State',
                'verbose_name_plural': 'Scheme Fund Requests By State',
            },
        ),
    ]
